import * as stylex from "@stylexjs/stylex";

const rise = stylex.keyframes({
  from: { opacity: 0, transform: "translate3d(0, 14px, 0)" },
  to: { opacity: 1, transform: "none" },
});

const spin = stylex.keyframes({
  to: { transform: "rotate(360deg)" },
});

const swift = "140ms cubic-bezier(0.4, 0, 0.2, 1)";
const glide = "320ms cubic-bezier(0.4, 0, 0.2, 1)";
const easeSettle = "cubic-bezier(0.16, 1, 0.3, 1)";
const body =
  '"Baloo 2", "Kohinoor Devanagari", "Nirmala UI", "Noto Sans Devanagari", ui-rounded, system-ui, sans-serif';

export const styles = stylex.create({
  dock: {
    animationName: rise,
    animationDuration: "620ms",
    animationTimingFunction: easeSettle,
    animationFillMode: "both",
    animationDelay: "0.16s",
    position: "relative",
    width: "100%",
    maxWidth: "30rem",
    marginBottom: "clamp(0.5rem, 7vh, 4.5rem)",
  },
  list: {
    position: "absolute",
    bottom: "calc(100% + 0.7rem)",
    left: 0,
    right: 0,
    zIndex: 5,
    maxHeight: "min(48dvh, 24rem)",
    overflowY: "auto",
    overscrollBehavior: "contain",
    borderRadius: "1.35rem",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    backgroundColor: "rgba(20, 20, 22, 0.55)",
    backdropFilter: "blur(28px) saturate(150%)",
    WebkitBackdropFilter: "blur(28px) saturate(150%)",
    boxShadow:
      "0 8px 40px rgba(0, 0, 0, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.25)",
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255, 255, 255, 0.28) transparent",
    opacity: 0,
    visibility: "hidden",
    transform: "translate3d(0, 10px, 0) scale(0.985)",
    transformOrigin: "bottom center",
    transition: `opacity ${glide}, transform ${glide}, visibility 0s linear 320ms`,
  },
  listOpen: {
    opacity: 1,
    visibility: "visible",
    transform: "none",
    transition: `opacity ${glide}, transform 420ms ${easeSettle}, visibility 0s`,
  },
  listItems: {
    margin: 0,
    padding: "0.4rem",
    listStyle: "none",
  },
  listButton: {
    width: "100%",
    display: "flex",
    alignItems: "baseline",
    gap: "0.6rem",
    padding: "0.45rem 0.7rem",
    border: "none",
    borderRadius: "0.7rem",
    backgroundColor: {
      default: "transparent",
      ":hover": "rgba(255, 255, 255, 0.12)",
    },
    color: {
      default: "rgba(255, 255, 255, 0.82)",
      ":hover": "#fff",
    },
    fontFamily: body,
    fontSize: "0.86rem",
    fontWeight: 600,
    textAlign: "left",
    cursor: {
      default: "pointer",
      ":disabled": "default",
    },
    transition: `background ${swift}, color ${swift}`,
    outline: {
      default: "none",
      ":focus-visible": "2px solid #fff",
    },
    outlineOffset: {
      default: 0,
      ":focus-visible": -2,
    },
  },
  listButtonCurrent: {
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    color: "#fff",
    fontWeight: 800,
  },
  listNumber: {
    flex: "none",
    width: "1.4rem",
    fontSize: "0.7rem",
    fontVariantNumeric: "tabular-nums",
    color: "rgba(255, 255, 255, 0.4)",
  },
  listTitle: {
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  listArtist: {
    fontSize: "0.74rem",
    fontWeight: 600,
    color: "rgba(255, 255, 255, 0.5)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  bumper: {
    width: "100%",
    margin: "0 auto 0.7rem",
    padding: "0 0.5rem",
    textAlign: "center",
    userSelect: "none",
  },
  bumperText: {
    fontFamily: `"Yatra One", ${body}`,
    fontSize: "clamp(1rem, 2.6vw, 1.28rem)",
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: "0.015em",
    textAlign: "center",
    textWrap: "balance",
    color: "rgba(255, 255, 255, 0.8)",
    textShadow: "0 1px 6px rgba(0, 0, 0, 0.55)",
    transition: "opacity 240ms ease",
  },
  bumperSwapping: { opacity: 0 },
  bumperNext: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    verticalAlign: "-0.22em",
    marginLeft: "0.4em",
    width: "1.4rem",
    height: "1.4rem",
    padding: 0,
    border: "none",
    borderRadius: "50%",
    backgroundColor: {
      default: "transparent",
      ":hover": "rgba(255, 255, 255, 0.15)",
    },
    color: {
      default: "rgba(255, 255, 255, 0.4)",
      ":hover": "#fff",
    },
    cursor: "pointer",
    transition: `color ${swift}, background ${swift}, rotate 420ms ${easeSettle}`,
    rotate: { ":active": "180deg" },
    outline: { default: "none", ":focus-visible": "2px solid #fff" },
    outlineOffset: { default: 0, ":focus-visible": 2 },
  },
  bumperIcon: {
    width: 14,
    height: 14,
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 2.2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  player: {
    display: "flex",
    alignItems: "center",
    gap: "0.7rem",
    padding: "0.4rem 0.9rem 0.4rem 0.4rem",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    backdropFilter: "blur(28px) saturate(150%)",
    WebkitBackdropFilter: "blur(28px) saturate(150%)",
    boxShadow:
      "0 8px 40px rgba(0, 0, 0, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.25)",
    flexWrap: {
      default: "nowrap",
      "@media (max-width: 640px)": "wrap",
    },
    rowGap: { default: null, "@media (max-width: 640px)": "0.6rem" },
    paddingBlock: { default: "0.4rem", "@media (max-width: 640px)": "0.75rem" },
    paddingInlineEnd: {
      default: "0.9rem",
      "@media (max-width: 640px)": "0.75rem",
    },
    borderRadius: { default: 999, "@media (max-width: 640px)": "1.5rem" },
  },
  disc: {
    position: "relative",
    width: {
      default: "3.25rem",
      "@media (max-width: 640px)": "3.75rem",
    },
    height: {
      default: "3.25rem",
      "@media (max-width: 640px)": "3.75rem",
    },
    flex: "none",
    transition: "transform 320ms cubic-bezier(0.4, 0, 0.2, 1)",
  },
  discPlaying: {
    transform: {
      default: "scale(1.03)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  discRing: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    overflow: "hidden",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.4)",
    outline: "1px solid rgba(255, 255, 255, 0.2)",
    outlineOffset: "-1px",
    backgroundColor: "#1a1a1a",
    animationName: {
      default: spin,
      "@media (prefers-reduced-motion: reduce)": null,
    },
    animationDuration: "8s",
    animationTimingFunction: "linear",
    animationIterationCount: "infinite",
    animationPlayState: "paused",
  },
  discRingPlaying: { animationPlayState: "running" },
  discArt: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  discArtBoxed: { transform: "scale(1.35)" },
  discHub: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: "0.5rem",
    height: "0.5rem",
    transform: "translate(-50%, -50%)",
    borderRadius: "50%",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    boxShadow: "0 0 0 2px rgba(255, 255, 255, 0.4)",
  },
  meta: { flex: 1, minWidth: 0 },
  metaTitle: {
    margin: 0,
    fontWeight: 700,
    fontSize: "0.84rem",
    lineHeight: 1.25,
    textShadow: "0 1px 2px rgba(0, 0, 0, 0.35)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    transition: "opacity 220ms ease",
  },
  metaArtist: {
    margin: 0,
    fontSize: "0.71rem",
    fontWeight: 600,
    lineHeight: 1.25,
    color: "rgba(255, 255, 255, 0.7)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    transition: "opacity 220ms ease",
  },
  metaSwap: { opacity: 0 },
  seek: {
    position: "relative",
    height: 10,
    marginTop: "0.2rem",
    cursor: "pointer",
    touchAction: "none",
    outline: { default: "none", ":focus-visible": "2px solid #fff" },
    outlineOffset: { default: 0, ":focus-visible": 3 },
  },
  seekRail: {
    position: "absolute",
    insetInline: 0,
    top: "50%",
    height: 3,
    transform: "translateY(-50%)",
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  seekFill: {
    height: "100%",
    width: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    transform: "scaleX(0)",
    transformOrigin: "left center",
    willChange: "transform",
  },
  seekKnob: {
    position: "absolute",
    top: "50%",
    left: 0,
    width: 10,
    height: 10,
    transform: "translate(-50%, -50%)",
    borderRadius: "50%",
    backgroundColor: "#fff",
    boxShadow: "0 1px 4px rgba(0, 0, 0, 0.5)",
    opacity: 0,
    transition: `opacity ${swift}`,
    willChange: "transform",
  },
  seekKnobVisible: { opacity: 1 },
  time: {
    marginTop: "0.05rem",
    fontSize: "0.62rem",
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    color: "rgba(255, 255, 255, 0.6)",
  },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: {
      default: "0.15rem",
      "@media (max-width: 640px)": "0.35rem",
    },
    flex: "none",
    width: { default: "auto", "@media (max-width: 640px)": "100%" },
    justifyContent: {
      default: "normal",
      "@media (max-width: 640px)": "center",
    },
  },
  btn: {
    display: "grid",
    placeItems: "center",
    width: "1.8rem",
    height: "1.8rem",
    border: "none",
    borderRadius: "50%",
    backgroundColor: {
      default: "transparent",
      ":hover": "rgba(255, 255, 255, 0.15)",
    },
    color: {
      default: "rgba(255, 255, 255, 0.8)",
      ":hover": "#fff",
    },
    cursor: {
      default: "pointer",
      ":disabled": "default",
    },
    transition: `background ${swift}, color ${swift}, transform ${swift}`,
    transform: { ":active": "scale(0.92)" },
    outline: { default: "none", ":focus-visible": "2px solid #fff" },
    outlineOffset: { default: 0, ":focus-visible": 2 },
  },
  btnSvg: { width: 15, height: 15, display: "block" },
  btnPlaySvg: { width: 17, height: 17, display: "block" },
  btnPlay: {
    width: "2.25rem",
    height: "2.25rem",
    backgroundColor: "#fff",
    color: "#000",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.35)",
    transform: {
      default: "none",
      ":hover": "scale(1.06)",
      ":disabled": "none",
    },
    opacity: { default: 1, ":disabled": 0.5 },
  },
  btnToggleOn: {
    color: "#fff",
    backgroundColor: {
      default: "rgba(255, 255, 255, 0.2)",
      ":hover": "rgba(255, 255, 255, 0.2)",
    },
  },
  ytHost: {
    position: "fixed",
    top: 0,
    left: 0,
    width: 1,
    height: 1,
    overflow: "hidden",
    visibility: "hidden",
    opacity: 0,
    pointerEvents: "none",
  },
});
